Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,19 +1,50 @@
+# Go
+# Build your Go project.
+# Add steps that test, save build artifacts, deploy, and more:
+# https://docs.microsoft.com/azure/devops/pipelines/languages/go
+
 trigger:
+- master
+
+pr:
 - master
 
 pool:
   vmImage: 'ubuntu-latest'
 
-variables:
-  GOBIN:  '$(GOPATH)/bin' # Go binaries path
-  GOROOT: '/usr/local/go1.11' # Go installation path
+variables:  
   GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
-  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
-  
+  GOBIN:  '$(GOPATH)/bin' # Go binaries path
+  PLUGIN_DIR: '$(GOBIN)'
+  modulePath: '$(GOPATH)/src/hello' # Path to the module's code
+
 steps:
 - script: |
-    echo $(modulePath)
+    echo "GOBIN $(GOBIN)"
+    echo "GOPATH $(GOPATH)"
+    echo "REPO PATH $(GOPATH)/src/github.com/$(build.repository.name)"
+
+    mkdir -p '$(GOPATH)'
+    mkdir -p '$(GOBIN)'
+    mkdir -p '$(GOPATH)/pkg'
+    mkdir -p '$(modulePath)'
+    echo "Moving $(system.defaultWorkingDirectory)/* To $(modulePath)"
+    mv $(system.defaultWorkingDirectory)/* $(modulePath)
+    shopt -s extglob
+    shopt -s dotglob
+    echo '##vso[task.prependpath]$(GOBIN)'
+    echo '##vso[task.prependpath]$(GOROOT)/bin'
+  displayName: 'Set up the Go workspace'
+
+- script: |
     go version
-    go run src/main.go
-  workingDirectory: '$(modulePath)'
+    if [ -f Gopkg.toml ]; then
+        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+        dep ensure
+    else
+      echo "ERROR no Gopkg.toml found!"
+      exit 1
+    fi
+    go run main.go
+  workingDirectory: '$(GOPATH)/src'
   displayName: 'Get dependencies, then build'
